<?php   
use Zend\Form\Element;

echo $this->headScript()->captureStart();

echo " $(document).ready(function(){
  $('#tb_padrao').DataTable();
    
    
});";

echo $this->headScript()->captureEnd();
echo "<div class='container'>";


$title = 'Cadastro de Usuários';
echo  $this->headTitle($title);
echo "<h1>".$this->escapeHtml($title)."</h1>";


$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    &times;
</button>
<div>')->setMessageCloseString('</div></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

echo "<a  class='btn btn-info' href=".$this->url('usuario', array('action'=>'add')).">Novo Usuário</a><br>";

echo '<br><table id="tb_padrao" border="0" class="display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>Login/Email</th>
                        <th>Nome</th>
                        <th>Papel</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
					</tr>
				</thead>

				<tbody>';

//$contador=0;

foreach ($this->registro as $_registro) {
    
   echo '<tr>';
   echo '<td>'.$this->escapeHtml($_registro->getEmail() ).' </td>';
   echo '<td>'.$this->escapeHtml($_registro->getLogin() ).' </td>';
    
    echo '<td>';
    
    foreach ($_registro->getPapel() as $papel)
    {
   	echo "<p>".$papel->getDescricao()."</p>";
    }
    echo ' </td>';
    
    echo '<td><a href="'.$this->url('usuario',
    		array('action'=>'edit', 'codigo' => $_registro->getCodigo())).'">Editar</a></td>';
    echo '<td><a href="'.$this->url('usuario',
		array('action'=>'delete', 'codigo' => $_registro->getCodigo() )).'">Remover</a></td>';
    echo '<td><a href="'.$this->url('usuario',
    		array('action'=>'password', 'codigo' => $_registro->getCodigo() )).'">Senha</a></td>';
    echo '</tr>';
   
}
echo '          </tbody>
    </table> </div>';

