<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Infra\Module'                        => __DIR__ . '/Module.php',
    'Infra\Controller\InfraController' => __DIR__ . '/src/Infra/Controller/InfraController.php',
    'InfraTest\Framework\TestCase'        => __DIR__ . '/tests/Infra/Framework/TestCase.php',
    'InfraTest\SampleTest'                => __DIR__ . '/tests/Infra/SampleTest.php',
);
