<?php
$title = 'Alteração de Senha';
$this->headTitle($title);

echo "<h1>".$this->escapeHtml($title)."</h1>";

echo "<h2>".$this->translate("Login").": ".$this->login."</h2>";
    
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    &times;
</button>
<div>')->setMessageCloseString('</div></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

    $form = $this->senha;

    $form->setAttribute('action', $this->url('usuario',
           array('action' => 'password', 'codigo' => $form->get('codigo')->getValue())));
    
    $form->prepare();
    
    echo $this->form()->openTag($form);
    
    echo '<div class="form-group">';
    $campo = $form->get('senha');
    echo $this->formRow($campo);
    echo "</div>";
    
    echo '<div class="form-group">';
    $campo = $form->get('senha1');
    echo $this->formRow($campo);
    echo "</div>";
    
    echo '<div class="form-group">';
    $campo = $form->get('csrf');
    echo $this->formRow($campo);
    echo "</div>";
    
    echo '<div class="form-group">';
    $campo = $form->get('submit');
    echo $this->formRow($campo);
    echo "</div>";
    
    //echo $this->formCollection($this->form);
    echo $this->form()->closeTag();
    echo '</div>';

 
 