<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/application.config.old
 */
return array(
    'modules' => array(
        'Application',
        'ZF\\DevelopmentMode',
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZF\\Apigility\\Documentation',
<<<<<<< HEAD
        'ZF\\Apigility\\Admin', //Ambiente administracao apigility
        'ZF\\Configuration',//ambiente administracao apigility comentar
=======
>>>>>>> c11d551e3e871d26d68e43531bcc177a24487914
        'DoctrineModule',
        'DoctrineORMModule',
        'Infra',
        'ZfrCors',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
<<<<<<< HEAD
=======
            './module',
            './module',
            './module',
            './module','./module',
>>>>>>> c11d551e3e871d26d68e43531bcc177a24487914
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
