<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Projeto BaseZero')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->appendStylesheet($this->basePath() . '/bower_components/jquery-ui/themes/redmond/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/bower_components/datatables/media/css/jquery.dataTables.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        				->prependStylesheet($this->basePath() . '/css/base.css')
         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/bower_components/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/base.js')
            ->appendFile($this->basePath() . '/bower_components/datatables/media/js/jquery.dataTables.min.js')
            ->appendFile($this->basePath() . '/js/busca/formcollection.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                    <img src="<?php echo $this->basePath('img/natural.png') ?>" alt="BaseZero"/>&nbsp;
                    <?php echo $this->translate('BaseZero') ?></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
            <?php $partial = array('application/navigation/topnav.phtml', 'default') ?>
            <?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
            <?php echo $this->navigation('navigation')->menu()->render() ?>
        </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> Projeto BaseZero - github: 
                   <a href=https://github.com/andreeppinghaus/BaseZero> https://github.com/andreeppinghaus/BaseZero</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
