<div class="jumbotron">
    <h2><?php echo sprintf($this->translate('%sProjeto BaseZero %s'), '<span class="zf-green">', '</span>') ?></h2>
    	É um sistema em PHP, construído com o Framework Zend  2 (Versão 2.4) com as seguintes características:
    	
    	<ul>
    		<li>Cadastro de usuários pelo admin</li>
    		<li>Cadastro de perfil de usuário</li>
    		<li>Menu configurável de acordo com o perfil do usuário</li>
    		<li>Gerador de Api's Apigility configurado e ativado</li>
    		<li>Doctrine 2 configurado e ativado</li>
    		
    	</ul>
	   <a class="btn btn-success" href="https://github.com/andreeppinghaus/BaseZero" target="_blank">
                 Download GitHub &raquo;</a>
	    </p>
</div>

<div class="row">

	<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bibliotecas e Frameworks utilizados</h3>
            </div>
            <div class="panel-body">
                <ul>
                	<li>
                		<a href=http://framework.zend.com/> Zend Framework 2</a>
                	</li>
                 	<li>
                    	<a href=https://apigility.org/> Apigility</a>
                 	</li>
                 	<li>
                    	<a href=https://github.com/doctrine/DoctrineModule>
                    		 DoctrineModule for Zend Framework 2
                    	</a>
                 	</li>
                 	<li>
                    	<a href=http://getbootstrap.com/> 
                    		Bootstrap.com
                    	</a>
                 	</li>
                 	<li>
                    	<a href=https://jquery.com/> JQuery</a>
                 	</li>
                 	<li>
                    	<a href=https://angularjs.org/> Angularjs 1</a>
                 	</li>
                 	<li>
                    	<a href=https://datatables.net/> 
                    		DataTables Table plug-in for jQuery
                    	</a>
                 	</li>
                 	
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Para quem se destina o projeto ?') ?></h3>
            </div>
            <div class="panel-body">
            <h4>A todas as pessoas queiram desenvolver 
                 sistemas utilizando o Zend Framework 2.0
            </h4>
            </div>
        </div>
    </div>
    
     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Começando</h3>
            </div>
            <div class="panel-body">
            <ul>
            <li><a href=#>Download e instalação do código em um servidor</a></li>
            <li><a href=#>Instalação das tabelas no banco de dados</a></li>
            <li><a href=#>Diagrama de Entidade e Relacionamento</a></li>
            <li><a href=#>UML</a></li>
            </ul>
            
            </div>
        </div>
    </div>

</div>
