AQUI
<div class="row">

	<div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Como Surgiu ?</h3>
            </div>
            <div class="panel-body">
                <p>
                <h4>teste  </h4>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Quem Somos ?') ?></h3>
            </div>
            <div class="panel-body">
            <h4> Empresa voltada para o desenvolvimento de aplicativos e sistemas Web.</h4>
            </div>
        </div>
    </div>
    

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Quem apoia o projeto ?') ?></h3>
            </div>
            <div class="panel-body">
            
                <h4><?php echo sprintf($this->translate('ADITEC - 
                    A Agência de Desenvolvimento e Inovação Tecnológica (ADITEC)
                    é um núcleo estratégico da Estácio, vinculado à diretoria acadêmica 
                    e à área de pesquisa aplicada, que visa gerir projetos de cunho inovador
                    firmados entre os docentes e alunos da Estácio e as empresas. ') ); 
                    ?>
                </h4>
                <p><a class="btn btn-success pull-right" href="http://www.estacio.br/aditec/" target="_blank">
                         <?php echo $this->translate('Site da ADITEC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
