<div class="row">

	<div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Como Surgiu ?</h3>
            </div>
            <div class="panel-body">
                <p>
                <h4>
                 O projeto BaseZero,  é um projeto open source de um sistema com os 
                 módulos básicos prontos (login e senha, perfil de usuários, etc), 
                 desenvolvido em PHP, Javascript, HTML 5 utilizando o Zend Framework 2 (ZF2).
                 </h4> 
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Quem Sou ?') ?></h3>
            </div>
            <div class="panel-body">
            <h4> Mestre em Avaliação pela Fundação Cesgranrio (2011), 
                especialização em Engenharia e Controle de Automação Industrial pela Universidade Gama Filho,
                 graduação em Tecnologia em Processamento de Dados pela Universidade Castelo Branco (1998). 
                 Atualmente é docente da Universidade Estácio de Sá no curso de Sistemas de Informação, 
                 atuando principalmente nos seguintes temas: Avaliação online, 
                  software livre, meta-avaliação e desenvolvimento de sistemas Web. 
                  Autor da ferramenta de avaliação online CheckTask da empresa Ambiente Tecnológico LTDA. </h4>
            </div>
        </div>
    </div>
    
</div>
